### Genome version considerations

# genome_name should match bams
genome_name: "hg38"

# RPKM matrix of the samples
matrix:  /projects/glchang_prj/POG_preprocess/expression_matrix.tsv

# Use phased vcf (True or False)
# Uses pseudphasing algorithm if False
phased: True

# Major allele frequency threshold for ASE (0.5 - 0.75)
maf_threshold: 0.65

# Threads for Strelka and MBASED
threads: 20

# Perform cancer analysis
# Need to include CNV data (from ploidetect) and allelic methyation (from NanoMethPhased)
cancer_analysis: True
