### Genome version considerations

# genome_name should match bams
genome_name: "hg38"

# RPKM matrix of the samples
matrix: /projects/glchang_prj/POG_preprocess/expression_matrix.tsv

# Use phased vcf or pseudophasing algorithm (True or False)
phased: False

### Defaults that can be left alone safely

output_dir: "ase-out"
temp_dir:
