### Genome version considerations

# genome_name should match bams
genome_name: "hg38"

# RPKM matrix of the samples
matrix: /projects/glchang_prj/ASE_snakemake/coriellCellLine/GM12878/GM12878_expression_matrix.tsv 

### Defaults that can be left alone safely

output_dir: "ase-out"
temp_dir:
