### Genome version considerations

# genome_name should match bams
genome_name: "hg38"

# RPKM matrix of the samples
matrix:  /projects/koneill_scratch/pog_tmp/GM24385/rna/rsem/expression_matrix.tsv

# Use phased vcf (True or False)
# Uses pseudphasing algorithm if False
phased: True
