# sample name must match the sample ID on the RPKM matrix
samples:
    exampleSample:
        rna:
            /path/to/RNA/alignment.bam
        phase:
            /path/to/phase.vcf # Does not need to be included if phase = False
        cnv:
            /path/to/cnv/data # Does not need to be included if cancer_analysis = False
        methyl:
            /path/to/methyl/data.bed # Does not need to be included if cancer_analysis = False
