# sample name must match the sample ID on the RPKM matrix
samples:
    GM12878_DNA:
        dna:
            /projects/glchang_prj/ASE_snakemake/coriellCellLine/GM12878/GM12878_DNA.sorted.bam 
        rna:
            /projects/glchang_prj/ASE_snakemake/coriellCellLine/GM12878/GM12878_RNA.bam 
        phase:
            /projects/glchang_prj/ASE_snakemake/coriellCellLine/GM12878/NA12878_Guppy6_Clair3_Passed_WhatsHapPhased.vcf
            
